# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
import pandas as pd
import numpy as np

import datetime
from dateutil.relativedelta import relativedelta

# Viz mantra
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline
%config Inlinebackend.figure_format = 'retina'
sns.set_context('poster')
sns.set(rc={'figure.figsize': (16., 9.)})
sns.set_style('whitegrid')

import plotly.express as px
import plotly.graph_objects as go

# Statsmodel
import statsmodels.api as sm
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.api import SimpleExpSmoothing
from statsmodels.tsa.seasonal import seasonal_decompose




# Scikit learn
from sklearn.linear_model import LinearRegression

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function.

In [2]:
from sklearn.datasets import load_diabetes

In [3]:
target = pd.DataFrame(load_diabetes().target, columns=["target"])


In [4]:
diabetes = pd.DataFrame(load_diabetes().data, columns=load_diabetes().feature_names)

Let's explore this variable by looking at the different attributes. Do this by looking at the `keys()` of this variable.

In [5]:
diabetes.keys()



Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

The next step is to read the description of the dataset. Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable

In [6]:
diabetes.describe


<bound method NDFrame.describe of           age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -

What are the variables in this dataset according to the description? List them in the markdown cell below

age	sex	bmi	bp	s1	s2	s3	s4	s5	s6

#### Enter your answer here:




Now explore the data. Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). In the cell below find the shape of the numpy array contained in the data portion of the diabetes variable.

In [7]:
diabetes.shape



(442, 10)

# Challenge 2 - Perform Supervised Learning on the Dataset

#### The data has already been split to predictor and response variables. The response variable is in the `target` portion of the variable. 

Given this information, let's apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset. In the cell below, import the linear regression class from sklearn. 

In [8]:
from sklearn.linear_model import LinearRegression as LinReg



In [9]:
linreg=LinReg()

In [10]:
linreg.fit(diabetes)

TypeError: fit() missing 1 required positional argument: 'y'

Initialize the model in the variable `diabetes_model`

In [16]:
diabetes_model = linreg.fit(diabetes, target)

In the cell below, fit the model and print the intercept and coefficients of the model. 

In [17]:
diabetes_model.coef_

array([[ 2.52820339e-13, -7.74935671e-13, -2.31073732e-13,
        -1.87740448e-13,  6.51932935e-13, -6.10173479e-13,
        -4.20258229e-13, -1.89863208e-13, -1.81083989e-13,
         2.94942022e-14,  1.00000000e+00]])

In [18]:
diabetes_model.intercept_

array([-2.84217094e-14])

# Bonus Challenge 1 - Conduct a Hypothesis Test on the Model

Once we have generated a linear model, we can test each coefficient using a t-test to see whether the confidence interval for the variable contains zero. We can also perform an overall F test to check whether at least one coefficient is significantly different from zero. 

Refer to the resource in this [link](https://onlinecourses.science.psu.edu/stat501/node/297/) for more details and perform the t-tests for the model above. Additionally, interpret the results and list coefficients are significantly different from zero.


Hint: use the statsmodels package.

Your result should look similar to this:

![ols](../ols-results.png)

In [19]:
import statsmodels.formula.api as smf

In [20]:
diabetes.head(1)

age      sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.05068  0.061696  0.021872 -0.044223 -0.034821 -0.043401   

         s4        s5        s6  target  
0 -0.002592  0.019908 -0.017646   151.0

In [21]:
diabetes["target"] = load_diabetes().target
mod = smf.ols(formula="target ~ age + sex + bmi + bp + s1 + s2 + s3 + s4 + s5 + s6", data=diabetes)
res = mod.fit()
print(res.summary())

                            OLS Regression Results                            
Dep. Variable:                 target   R-squared:                       0.518
Model:                            OLS   Adj. R-squared:                  0.507
Method:                 Least Squares   F-statistic:                     46.27
Date:                Thu, 18 Aug 2022   Prob (F-statistic):           3.83e-62
Time:                        16:41:12   Log-Likelihood:                -2386.0
No. Observations:                 442   AIC:                             4794.
Df Residuals:                     431   BIC:                             4839.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    152.1335      2.576     59.061      0.0

# Challenge 2 - Peform Supervised Learning on a Pandas Dataframe

Now that we have looked at data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [22]:
auto = pd.read_csv('../auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [23]:
auto.head(5)


mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

In [24]:
auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horse_power   392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   car_name      398 non-null    object 
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB


Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [25]:
auto.dtypes



mpg             float64
cylinders         int64
displacement    float64
horse_power     float64
weight            int64
acceleration    float64
model_year        int64
car_name         object
dtype: object

What is the newest model year and the oldest model year?

In [26]:
newest_model = auto["model_year"].max()
oldest_model = auto["model_year"].min()
print(newest_model)
print(oldest_model)

82
70


Check the dataset for missing values and remove all rows containing at least one missing value.

In [27]:
df = auto.dropna()


Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [28]:
df["cylinders"].value_counts().count()

5

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

In [29]:
df = df.drop('car_name', axis=1)


In [30]:
y = df["mpg"]
X = df.drop("mpg", axis=1)

from sklearn.model_selection import train_test_split as tts

X_train, X_test, y_train, y_test = tts(X , y, test_size=0.2)


Now we will the dataset that we processed and peform linear regression on this data to predict the mpg for each vehicle. Initialize the model in the cell below.

In [31]:
linreg=LinReg()





Next, fit the model in the cell below.

In [32]:
linreg.fit(X_train, y_train)



LinearRegression()

# Challenge 3 - Evaluate the Model

the r squared score of a model tells us how much variation is explained by the model. In a typical dataset, most observations differ from the mean. When we create a model, we are trying to generate an equation that will tell us by how much each observation will differ from the mean. Obviously, the vast majority of models are not perfect. They can only predict some of the variation from the mean but not all of it. We attribute the rest of the difference between the actual value and the mean to random error. We would like random error to explain the as little as possible of the variation. This is why the r squared score is an important metric.

In the next cell, compute the r squared score of the model. Do this by first computing the predicted values and assign them to `y_pred`.

In [33]:
from sklearn import metrics
import numpy as np

In [34]:
y_pred = linreg.predict(X_test)
y_pred.shape

(79,)

In [35]:
print('MAE - Mean absolute error', metrics.mean_absolute_error(y_test, y_pred)) ## eror que fas de mitja
print('MSE - Mean squared error', metrics.mean_squared_error(y_test, y_pred)) ## error que no ens importa
print('RMSE - Root mean squared error', np.sqrt(metrics.mean_squared_error(y_test, y_pred))) ## arrel del error que no ens importa
print('R2 - Coefficient of determination', metrics.r2_score(y_test, y_pred)) # lo bo que es el teu model,
#quan mes a prop del 1 que estigui millor es el teu model.

MAE - Mean absolute error 2.6453714161681536
MSE - Mean squared error 12.463415014391925
RMSE - Root mean squared error 3.5303562163600324
R2 - Coefficient of determination 0.8028599609714584


#### Our next step is to evaluate the model using the test data. We would like to ensure that our model is not overfitting the data. This means that our model will not be able to generalize well outside of the training data.

In the cell below, use the model to generate the predicted values for the training data and assign them to `y_test_pred`. Compute the r squared score for the test data by comparing the oberserved `y_test` data and the predicted `y_test_pred`.

In [36]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

In [37]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=3, step=1)
selector = selector.fit(X_test, y_test)
selector.support_

array([ True, False, False, False,  True,  True])

# Challenge 4 - Improve the Model Fit

While the most common way to improve the fit of a model is by using regularization, there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [38]:

import numpy as np 
import pandas as pd
import matplotlib.pyplot 
%matplotlib inline
import seaborn as sns 
import warnings 
warnings.filterwarnings('ignore')


In [39]:
from sklearn.metrics import r2_score
from sklearn import metrics

##REGULARIZATION

# alpha=0 is equivalent to linear regression
from sklearn.linear_model import Ridge
ridgereg = Ridge(alpha=0, normalize=True)
ridgereg.fit(X_train, y_train)
y_pred = ridgereg.predict(X_test)

# calculate R^2 value, MAE, MSE, RMSE
from sklearn import metrics
print("R-Square Value",r2_score(y_test,y_pred))
print("\n")
print ("mean_absolute_error :",metrics.mean_absolute_error(y_test, y_pred))
print("\n")
print ("mean_squared_error : ",metrics.mean_squared_error(y_test, y_pred))
print("\n")
print ("root_mean_squared_error : ",np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

R-Square Value 0.8028599609714582


mean_absolute_error : 2.6453714161681545


mean_squared_error :  12.463415014391941


root_mean_squared_error :  3.530356216360035


In [40]:
# try alpha=0.1
ridgereg = Ridge(alpha=0.1, normalize=True)
ridgereg.fit(X_train, y_train)
y_pred = ridgereg.predict(X_test)

# calculate R^2 value, MAE, MSE, RMSE


print("R-Square Value",r2_score(y_test,y_pred))
print("\n")
print ("mean_absolute_error :",metrics.mean_absolute_error(y_test, y_pred))
print("\n")
print ("mean_squared_error : ",metrics.mean_squared_error(y_test, y_pred))
print("\n")
print ("root_mean_squared_error : ",np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

print("//////////////////////////////////////////////////////////////////////////")

# examing the coefficients
print(ridgereg.coef_)

R-Square Value 0.7772942981328927


mean_absolute_error : 2.8013419215270385


mean_squared_error :  14.079704975808284


root_mean_squared_error :  3.7522932955471755
//////////////////////////////////////////////////////////////////////////
[-0.49719872 -0.00973063 -0.01967014 -0.00367043 -0.02459041  0.61068731]


In [41]:
##IMPROVING SIZE
X_train09, X_test09, y_train09, y_test09 = tts(X , y, test_size=0.9)

Initialize a new model. Name this model `auto_model09`. Fit the model to the new sample data.

In [42]:
linreg=LinReg()
linreg.fit(X_train09, y_train09)
auto_model09 = linreg.predict(X_test09)

print("R-Square Value",r2_score(y_test09,auto_model09))
print("\n")
print ("mean_absolute_error :",metrics.mean_absolute_error(y_test09,auto_model09))
print("\n")
print ("mean_squared_error : ",metrics.mean_squared_error(y_test09,auto_model09))
print("\n")
print ("root_mean_squared_error : ",np.sqrt(metrics.mean_squared_error(y_test09,auto_model09)))

R-Square Value 0.749093815035977


mean_absolute_error : 2.9625628865162263


mean_squared_error :  15.657440158358508


root_mean_squared_error :  3.9569483391066034


Compute the predicted values and r squared score for our new model and new sample data.

In [45]:
print("NEW VALUES")
print("/////////////////////////////////")
print("R-Square Value",r2_score(y_test09,auto_model09))
print("\n")
print ("mean_absolute_error :",metrics.mean_absolute_error(y_test09,auto_model09))
print("\n")
print ("mean_squared_error : ",metrics.mean_squared_error(y_test09,auto_model09))
print("\n")
print ("root_mean_squared_error : ",np.sqrt(metrics.mean_squared_error(y_test09,auto_model09)))



NEW VALUES
/////////////////////////////////
R-Square Value 0.749093815035977


mean_absolute_error : 2.9625628865162263


mean_squared_error :  15.657440158358508


root_mean_squared_error :  3.9569483391066034


In [46]:
print("OLD VALUES")
print("////////////////////////////////////////////////")
print("R-Square Value",r2_score(y_test,y_pred))
print("\n")
print ("mean_absolute_error :",metrics.mean_absolute_error(y_test, y_pred))
print("\n")
print ("mean_squared_error : ",metrics.mean_squared_error(y_test, y_pred))
print("\n")
print ("root_mean_squared_error : ",np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

OLD VALUES
////////////////////////////////////////////////
R-Square Value 0.7772942981328927


mean_absolute_error : 2.8013419215270385


mean_squared_error :  14.079704975808284


root_mean_squared_error :  3.7522932955471755


Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [47]:
print("OLD R-Square Value",r2_score(y_test,y_pred))
print("NEW R-Square Value",r2_score(y_test09,auto_model09))

OLD R-Square Value 0.7772942981328927
NEW R-Square Value 0.749093815035977


# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [ ]:
# Your code here:



Fit the model and print the ranking

In [ ]:
# Your code here:



Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [ ]:
# Your code here:



Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [ ]:
# Your code here: 

