# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [4]:
# Import your libraries:
import pandas as pd
import numpy as np
import warnings

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge, Lasso
from sklearn.linear_model import SGDRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_val_score as cvs
from sklearn.feature_selection import RFE
from sklearn.datasets import load_boston
from sklearn.svm import SVR
from sklearn import metrics


In [31]:
diabetez = pd.DataFrame(load_diabetes().data, columns=load_diabetes().feature_names)

In [34]:
diabetez["target"] = load_diabetes().target

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function.

In [24]:
# Your code here:
from sklearn.datasets import load_diabetes

diabetes = load_diabetes()
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

Let's explore this variable by looking at the different attributes. Do this by looking at the `keys()` of this variable.

In [25]:
# Your code here:
diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

The next step is to read the description of the dataset. Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable

In [26]:
# Your code here:
diabetes.DESCR

'.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, total serum cholesterol\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, total cholesterol / HDL\n      - s5      ltg, possibly log of serum triglycerides level\n      - s6      glu, blood sugar

What are the variables in this dataset according to the description? List them in the markdown cell below

#### Enter your answer here:




Now explore the data. Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). In the cell below find the shape of the numpy array contained in the data portion of the diabetes variable.

In [27]:
# Your code here:
diabetes.data.shape

(442, 10)

# Challenge 2 - Perform Supervised Learning on the Dataset

#### The data has already been split to predictor and response variables. The response variable is in the `target` portion of the variable. 

Given this information, let's apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset. In the cell below, import the linear regression class from sklearn. 

In [28]:
# Done above 

Initialize the model in the variable `diabetes_model`

In [29]:
lr = LinearRegression()

In [35]:
# Your code here:
X = diabetez.drop("target", axis=1)
y = diabetez.target

In the cell below, fit the model and print the intercept and coefficients of the model. 

In [36]:
# Your code here:
diabetez.sample()

age       sex       bmi        bp       s1        s2        s3  \
37 -0.009147 -0.044642  0.011039 -0.057313 -0.02496 -0.042963  0.030232   

          s4        s5       s6  target  
37 -0.039493  0.017036 -0.00522   276.0

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [38]:
model = lr.fit(X_train, y_train)

In [39]:
y_pred = model.predict(X_test)

In [40]:
y_pred[0]


191.99455230777588

In [41]:
model.coef_


array([   5.54487426, -237.26051799,  531.28029978,  314.72959705,
       -946.95908276,  594.16346251,  156.90613132,  198.11185268,
        814.80448687,   69.02434195])

In [42]:
model.intercept_

150.91541111792336

# Bonus Challenge 1 - Conduct a Hypothesis Test on the Model

Once we have generated a linear model, we can test each coefficient using a t-test to see whether the confidence interval for the variable contains zero. We can also perform an overall F test to check whether at least one coefficient is significantly different from zero. 

Refer to the resource in this [link](https://onlinecourses.science.psu.edu/stat501/node/297/) for more details and perform the t-tests for the model above. Additionally, interpret the results and list coefficients are significantly different from zero.


Hint: use the statsmodels package.

Your result should look similar to this:

![ols](../ols-results.png)

In [182]:
# Your code here:



# Challenge 2 - Peform Supervised Learning on a Pandas Dataframe

Now that we have looked at data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [43]:
# Your code here:
auto = pd.read_csv('../auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [44]:
# Your code here:
auto.head(5)


mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [47]:
# Your code here:
auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horse_power     float64
weight            int64
acceleration    float64
model_year        int64
car_name         object
dtype: object

What is the newest model year and the oldest model year?

In [53]:
# Your code here:
auto['model_year'].max()

82

In [77]:
auto['model_year'].min()

70

Check the dataset for missing values and remove all rows containing at least one missing value.

In [59]:
# first check then switch code around
auto.dropna(axis=0, inplace=True)
auto.isna().sum()

mpg             0
cylinders       0
displacement    0
horse_power     0
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [61]:
# Your code here:
auto['cylinders'].value_counts()

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

In [67]:
# Import the necessary function
auto.drop(['car_name'], axis=1)

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0    18.0          8         307.0        130.0    3504          12.0   
1    15.0          8         350.0        165.0    3693          11.5   
2    18.0          8         318.0        150.0    3436          11.0   
3    16.0          8         304.0        150.0    3433          12.0   
4    17.0          8         302.0        140.0    3449          10.5   
..    ...        ...           ...          ...     ...           ...   
393  27.0          4         140.0         86.0    2790          15.6   
394  44.0          4          97.0         52.0    2130          24.6   
395  32.0          4         135.0         84.0    2295          11.6   
396  28.0          4         120.0         79.0    2625          18.6   
397  31.0          4         119.0         82.0    2720          19.4   

     model_year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[392 rows x 7 columns]

In [70]:
# Your code here:
Y_train = auto.drop("mpg", axis=1)
X_train = auto.mpg

Now we will the dataset that we processed and peform linear regression on this data to predict the mpg for each vehicle. Initialize the model in the cell below.

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

Next, fit the model in the cell below.

In [73]:
model = lr.fit(X_train, y_train)

In [75]:
model.coef_

array([   -2.31887117,  -256.31802504,   542.71065007,   295.44439661,
       -1067.48017661,   748.28297388,   152.21195741,   162.7705485 ,
         834.79670374,    90.73068603])

In [76]:
model.intercept_

153.80646208320422

In [79]:
y_pred = model.predict(X_test)
y_pred

array([164.98136844, 251.06672067, 247.80455663, 219.14718455,
       111.04556148, 195.10861071, 186.64309554,  97.88232344,
        71.39021009, 207.25659552, 175.53959047, 110.38608728,
        51.52601259, 178.62197636, 184.56811299, 103.04701545,
        26.0929543 ,  49.86742728, 229.69995864,  48.72691925,
        83.65484433, 101.01293488, 176.68929661, 175.58860831,
       225.00584297, 180.28336602,  78.4722715 , 246.67905842,
       247.10846678, 165.64522298, 239.76817696, 181.62752822,
       258.89177068,  43.11199375, 117.39963028,  97.90914349,
       236.85370525, 150.68251023, 155.98135084, 161.56907879,
       205.73109968, 127.11609606, 166.92947621, 241.16970604,
       249.53724237, 193.92687988, 261.58483628, 150.9978129 ,
       125.1697583 , 186.59797912, 170.96096524,  68.09199074,
       121.96415992, 201.24900809, 205.90690535, 185.49957802,
        58.21420757, 129.00096807,  78.25760363, 171.44180681,
       284.7308246 , 200.4136556 , 130.59155019, 123.94

# Challenge 3 - Evaluate the Model

the r squared score of a model tells us how much variation is explained by the model. In a typical dataset, most observations differ from the mean. When we create a model, we are trying to generate an equation that will tell us by how much each observation will differ from the mean. Obviously, the vast majority of models are not perfect. They can only predict some of the variation from the mean but not all of it. We attribute the rest of the difference between the actual value and the mean to random error. We would like random error to explain the as little as possible of the variation. This is why the r squared score is an important metric.

In the next cell, compute the r squared score of the model. Do this by first computing the predicted values and assign them to `y_pred`.

In [84]:
# Your code here:
r2 = metrics.r2_score(y_test, y_pred)
r2

0.5231791703724382

#### Our next step is to evaluate the model using the test data. We would like to ensure that our model is not overfitting the data. This means that our model will not be able to generalize well outside of the training data.

In the cell below, use the model to generate the predicted values for the training data and assign them to `y_test_pred`. Compute the r squared score for the test data by comparing the oberserved `y_test` data and the predicted `y_test_pred`.

In [87]:
print('MAE: ', metrics.mean_absolute_error(y_test, y_pred))
print('MSE: ', metrics.mean_squared_error(y_test, y_pred))
print('RMSE: ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('R2: ', metrics.r2_score(y_test, y_pred) )

MAE:  44.54270252358802
MSE:  2958.6362266535366
RMSE:  54.393347264656704
R2:  0.5231791703724382


# Challenge 4 - Improve the Model Fit

While the most common way to improve the fit of a model is by using regularization, there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [89]:
# Your code here:
Y_train = auto.drop("mpg", axis=1)
X_train = auto.mpg
X_train09, X_test09, y_train09, y_test09 = train_test_split(X,y, test_size = 0.1)

Initialize a new model. Name this model `auto_model09`. Fit the model to the new sample data.

In [91]:
# Your code here:
auto_model09 = LinearRegression()
auto_model09 = auto_model09.fit(X_train09, y_train09)
auto_model09

LinearRegression()

Compute the predicted values and r squared score for our new model and new sample data.

In [93]:
# Your code here:
y_pred09 = auto_model09.predict(X_test09)
y_pred09

array([186.1067886 , 160.59903125, 160.71446794,  26.7324717 ,
       122.86240721, 112.24672182, 175.16271859, 196.70167308,
       182.40717603, 167.09243437, 145.31191249, 122.99895007,
       245.38510062, 170.62949898,  95.81134851,  58.04432721,
        99.86874338, 151.46853527, 240.28625752,  84.11350443,
       237.86237589,  67.8611847 ,  75.51605722, 110.90238421,
        82.33369631, 144.3716509 ,  98.6265255 , 210.76973976,
       187.19722718,  42.62505792,  65.69465951, 178.53415833,
       119.70948507, 100.2381401 , 247.49277487, 112.90322726,
        72.65798209, 148.6867369 , 102.77775375, 101.05270028,
       128.1063231 ,  93.90776506,  55.54092303,  79.39090775,
       175.20702442])

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [97]:
# Your code here:
r2 = metrics.r2_score(y_test09, y_pred09)
r2

0.6264856325740443

# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [200]:
# Your code here:



Fit the model and print the ranking

In [201]:
# Your code here:



Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [202]:
# Your code here:



Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [203]:
# Your code here: 

